/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cwaf_config_buf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cwaf_config_buf.pb-c.h"
void   dns_config__init
                     (DnsConfig         *message)
{
  static const DnsConfig init_value = DNS_CONFIG__INIT;
  *message = init_value;
}
size_t dns_config__get_packed_size
                     (const DnsConfig *message)
{
  assert(message->base.descriptor == &dns_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dns_config__pack
                     (const DnsConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dns_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dns_config__pack_to_buffer
                     (const DnsConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dns_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DnsConfig *
       dns_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DnsConfig *)
     protobuf_c_message_unpack (&dns_config__descriptor,
                                allocator, len, data);
}
void   dns_config__free_unpacked
                     (DnsConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dns_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   static_route__init
                     (StaticRoute         *message)
{
  static const StaticRoute init_value = STATIC_ROUTE__INIT;
  *message = init_value;
}
size_t static_route__get_packed_size
                     (const StaticRoute *message)
{
  assert(message->base.descriptor == &static_route__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t static_route__pack
                     (const StaticRoute *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &static_route__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t static_route__pack_to_buffer
                     (const StaticRoute *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &static_route__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StaticRoute *
       static_route__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StaticRoute *)
     protobuf_c_message_unpack (&static_route__descriptor,
                                allocator, len, data);
}
void   static_route__free_unpacked
                     (StaticRoute *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &static_route__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   default_gateway__init
                     (DefaultGateway         *message)
{
  static const DefaultGateway init_value = DEFAULT_GATEWAY__INIT;
  *message = init_value;
}
size_t default_gateway__get_packed_size
                     (const DefaultGateway *message)
{
  assert(message->base.descriptor == &default_gateway__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t default_gateway__pack
                     (const DefaultGateway *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &default_gateway__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t default_gateway__pack_to_buffer
                     (const DefaultGateway *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &default_gateway__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DefaultGateway *
       default_gateway__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DefaultGateway *)
     protobuf_c_message_unpack (&default_gateway__descriptor,
                                allocator, len, data);
}
void   default_gateway__free_unpacked
                     (DefaultGateway *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &default_gateway__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   manage_service__init
                     (ManageService         *message)
{
  static const ManageService init_value = MANAGE_SERVICE__INIT;
  *message = init_value;
}
size_t manage_service__get_packed_size
                     (const ManageService *message)
{
  assert(message->base.descriptor == &manage_service__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t manage_service__pack
                     (const ManageService *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &manage_service__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t manage_service__pack_to_buffer
                     (const ManageService *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &manage_service__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ManageService *
       manage_service__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ManageService *)
     protobuf_c_message_unpack (&manage_service__descriptor,
                                allocator, len, data);
}
void   manage_service__free_unpacked
                     (ManageService *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &manage_service__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interface__init
                     (Interface         *message)
{
  static const Interface init_value = INTERFACE__INIT;
  *message = init_value;
}
size_t interface__get_packed_size
                     (const Interface *message)
{
  assert(message->base.descriptor == &interface__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interface__pack
                     (const Interface *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interface__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interface__pack_to_buffer
                     (const Interface *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interface__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interface *
       interface__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interface *)
     protobuf_c_message_unpack (&interface__descriptor,
                                allocator, len, data);
}
void   interface__free_unpacked
                     (Interface *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interface__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   match_option__init
                     (MatchOption         *message)
{
  static const MatchOption init_value = MATCH_OPTION__INIT;
  *message = init_value;
}
size_t match_option__get_packed_size
                     (const MatchOption *message)
{
  assert(message->base.descriptor == &match_option__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t match_option__pack
                     (const MatchOption *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &match_option__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t match_option__pack_to_buffer
                     (const MatchOption *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &match_option__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MatchOption *
       match_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MatchOption *)
     protobuf_c_message_unpack (&match_option__descriptor,
                                allocator, len, data);
}
void   match_option__free_unpacked
                     (MatchOption *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &match_option__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   define_rule__init
                     (DefineRule         *message)
{
  static const DefineRule init_value = DEFINE_RULE__INIT;
  *message = init_value;
}
size_t define_rule__get_packed_size
                     (const DefineRule *message)
{
  assert(message->base.descriptor == &define_rule__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t define_rule__pack
                     (const DefineRule *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &define_rule__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t define_rule__pack_to_buffer
                     (const DefineRule *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &define_rule__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DefineRule *
       define_rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DefineRule *)
     protobuf_c_message_unpack (&define_rule__descriptor,
                                allocator, len, data);
}
void   define_rule__free_unpacked
                     (DefineRule *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &define_rule__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl_certificate__init
                     (SslCertificate         *message)
{
  static const SslCertificate init_value = SSL_CERTIFICATE__INIT;
  *message = init_value;
}
size_t ssl_certificate__get_packed_size
                     (const SslCertificate *message)
{
  assert(message->base.descriptor == &ssl_certificate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl_certificate__pack
                     (const SslCertificate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl_certificate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl_certificate__pack_to_buffer
                     (const SslCertificate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl_certificate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SslCertificate *
       ssl_certificate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SslCertificate *)
     protobuf_c_message_unpack (&ssl_certificate__descriptor,
                                allocator, len, data);
}
void   ssl_certificate__free_unpacked
                     (SslCertificate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl_certificate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bizserver__init
                     (Bizserver         *message)
{
  static const Bizserver init_value = BIZSERVER__INIT;
  *message = init_value;
}
size_t bizserver__get_packed_size
                     (const Bizserver *message)
{
  assert(message->base.descriptor == &bizserver__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bizserver__pack
                     (const Bizserver *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bizserver__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bizserver__pack_to_buffer
                     (const Bizserver *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bizserver__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bizserver *
       bizserver__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bizserver *)
     protobuf_c_message_unpack (&bizserver__descriptor,
                                allocator, len, data);
}
void   bizserver__free_unpacked
                     (Bizserver *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bizserver__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   attack_detect__init
                     (AttackDetect         *message)
{
  static const AttackDetect init_value = ATTACK_DETECT__INIT;
  *message = init_value;
}
size_t attack_detect__get_packed_size
                     (const AttackDetect *message)
{
  assert(message->base.descriptor == &attack_detect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t attack_detect__pack
                     (const AttackDetect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &attack_detect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t attack_detect__pack_to_buffer
                     (const AttackDetect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &attack_detect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AttackDetect *
       attack_detect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AttackDetect *)
     protobuf_c_message_unpack (&attack_detect__descriptor,
                                allocator, len, data);
}
void   attack_detect__free_unpacked
                     (AttackDetect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &attack_detect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   site_security__init
                     (SiteSecurity         *message)
{
  static const SiteSecurity init_value = SITE_SECURITY__INIT;
  *message = init_value;
}
size_t site_security__get_packed_size
                     (const SiteSecurity *message)
{
  assert(message->base.descriptor == &site_security__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t site_security__pack
                     (const SiteSecurity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &site_security__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t site_security__pack_to_buffer
                     (const SiteSecurity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &site_security__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SiteSecurity *
       site_security__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SiteSecurity *)
     protobuf_c_message_unpack (&site_security__descriptor,
                                allocator, len, data);
}
void   site_security__free_unpacked
                     (SiteSecurity *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &site_security__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   predef_sign_rule__init
                     (PredefSignRule         *message)
{
  static const PredefSignRule init_value = PREDEF_SIGN_RULE__INIT;
  *message = init_value;
}
size_t predef_sign_rule__get_packed_size
                     (const PredefSignRule *message)
{
  assert(message->base.descriptor == &predef_sign_rule__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t predef_sign_rule__pack
                     (const PredefSignRule *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &predef_sign_rule__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t predef_sign_rule__pack_to_buffer
                     (const PredefSignRule *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &predef_sign_rule__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PredefSignRule *
       predef_sign_rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PredefSignRule *)
     protobuf_c_message_unpack (&predef_sign_rule__descriptor,
                                allocator, len, data);
}
void   predef_sign_rule__free_unpacked
                     (PredefSignRule *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &predef_sign_rule__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   virtual_service__init
                     (VirtualService         *message)
{
  static const VirtualService init_value = VIRTUAL_SERVICE__INIT;
  *message = init_value;
}
size_t virtual_service__get_packed_size
                     (const VirtualService *message)
{
  assert(message->base.descriptor == &virtual_service__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t virtual_service__pack
                     (const VirtualService *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &virtual_service__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t virtual_service__pack_to_buffer
                     (const VirtualService *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &virtual_service__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VirtualService *
       virtual_service__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VirtualService *)
     protobuf_c_message_unpack (&virtual_service__descriptor,
                                allocator, len, data);
}
void   virtual_service__free_unpacked
                     (VirtualService *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &virtual_service__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   virtual_service_res__init
                     (VirtualServiceRes         *message)
{
  static const VirtualServiceRes init_value = VIRTUAL_SERVICE_RES__INIT;
  *message = init_value;
}
size_t virtual_service_res__get_packed_size
                     (const VirtualServiceRes *message)
{
  assert(message->base.descriptor == &virtual_service_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t virtual_service_res__pack
                     (const VirtualServiceRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &virtual_service_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t virtual_service_res__pack_to_buffer
                     (const VirtualServiceRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &virtual_service_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VirtualServiceRes *
       virtual_service_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VirtualServiceRes *)
     protobuf_c_message_unpack (&virtual_service_res__descriptor,
                                allocator, len, data);
}
void   virtual_service_res__free_unpacked
                     (VirtualServiceRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &virtual_service_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cw_config__init
                     (CwConfig         *message)
{
  static const CwConfig init_value = CW_CONFIG__INIT;
  *message = init_value;
}
size_t cw_config__get_packed_size
                     (const CwConfig *message)
{
  assert(message->base.descriptor == &cw_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cw_config__pack
                     (const CwConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cw_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cw_config__pack_to_buffer
                     (const CwConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cw_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CwConfig *
       cw_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CwConfig *)
     protobuf_c_message_unpack (&cw_config__descriptor,
                                allocator, len, data);
}
void   cw_config__free_unpacked
                     (CwConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cw_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dns_config__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DnsConfig, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DnsConfig, interface_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DnsConfig, host_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preferred_server",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DnsConfig, preferred_server),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alternative_server",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DnsConfig, alternative_server),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dns_config__field_indices_by_name[] = {
  4,   /* field[4] = alternative_server */
  2,   /* field[2] = host_name */
  0,   /* field[0] = id */
  1,   /* field[1] = interface_name */
  3,   /* field[3] = preferred_server */
};
static const ProtobufCIntRange dns_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dns_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DnsConfig",
  "DnsConfig",
  "DnsConfig",
  "",
  sizeof(DnsConfig),
  5,
  dns_config__field_descriptors,
  dns_config__field_indices_by_name,
  1,  dns_config__number_ranges,
  (ProtobufCMessageInit) dns_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor static_route__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StaticRoute, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StaticRoute, interface_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StaticRoute, dst_ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subnet_mask",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StaticRoute, subnet_mask),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StaticRoute, gateway),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned static_route__field_indices_by_name[] = {
  2,   /* field[2] = dst_ip */
  4,   /* field[4] = gateway */
  0,   /* field[0] = id */
  1,   /* field[1] = interface_name */
  3,   /* field[3] = subnet_mask */
};
static const ProtobufCIntRange static_route__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor static_route__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StaticRoute",
  "StaticRoute",
  "StaticRoute",
  "",
  sizeof(StaticRoute),
  5,
  static_route__field_descriptors,
  static_route__field_indices_by_name,
  1,  static_route__number_ranges,
  (ProtobufCMessageInit) static_route__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor default_gateway__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DefaultGateway, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DefaultGateway, interface_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_gateway",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DefaultGateway, ipv4_gateway),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_gateway",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DefaultGateway, ipv6_gateway),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned default_gateway__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = interface_name */
  2,   /* field[2] = ipv4_gateway */
  3,   /* field[3] = ipv6_gateway */
};
static const ProtobufCIntRange default_gateway__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor default_gateway__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DefaultGateway",
  "DefaultGateway",
  "DefaultGateway",
  "",
  sizeof(DefaultGateway),
  4,
  default_gateway__field_descriptors,
  default_gateway__field_indices_by_name,
  1,  default_gateway__number_ranges,
  (ProtobufCMessageInit) default_gateway__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor manage_service__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ManageService, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ManageService, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ManageService, port),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "whitelist",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ManageService, whitelist),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ser_interface",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ManageService, ser_interface),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned manage_service__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  2,   /* field[2] = port */
  4,   /* field[4] = ser_interface */
  3,   /* field[3] = whitelist */
};
static const ProtobufCIntRange manage_service__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor manage_service__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ManageService",
  "ManageService",
  "ManageService",
  "",
  sizeof(ManageService),
  5,
  manage_service__field_descriptors,
  manage_service__field_indices_by_name,
  1,  manage_service__number_ranges,
  (ProtobufCMessageInit) manage_service__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interface__field_descriptors[10] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Interface, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interface, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Interface, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Interface, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interface, ipv4),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interface, ipv6),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interface, mac),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtu",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Interface, mtu),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "negotiate",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Interface, negotiate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "half",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Interface, half),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interface__field_indices_by_name[] = {
  9,   /* field[9] = half */
  0,   /* field[0] = id */
  4,   /* field[4] = ipv4 */
  5,   /* field[5] = ipv6 */
  6,   /* field[6] = mac */
  7,   /* field[7] = mtu */
  1,   /* field[1] = name */
  8,   /* field[8] = negotiate */
  3,   /* field[3] = speed */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange interface__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor interface__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Interface",
  "Interface",
  "Interface",
  "",
  sizeof(Interface),
  10,
  interface__field_descriptors,
  interface__field_indices_by_name,
  1,  interface__number_ranges,
  (ProtobufCMessageInit) interface__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor match_option__field_descriptors[3] =
{
  {
    "field",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MatchOption, field),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_rule",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MatchOption, match_rule),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expression",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MatchOption, expression),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned match_option__field_indices_by_name[] = {
  2,   /* field[2] = expression */
  0,   /* field[0] = field */
  1,   /* field[1] = match_rule */
};
static const ProtobufCIntRange match_option__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor match_option__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MatchOption",
  "MatchOption",
  "MatchOption",
  "",
  sizeof(MatchOption),
  3,
  match_option__field_descriptors,
  match_option__field_indices_by_name,
  1,  match_option__number_ranges,
  (ProtobufCMessageInit) match_option__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor define_rule__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DefineRule, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DefineRule, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DefineRule, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DefineRule, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DefineRule, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_type",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DefineRule, log_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DefineRule, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "match_option_list",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DefineRule, n_match_option_list),
    offsetof(DefineRule, match_option_list),
    &match_option__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expire_time",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DefineRule, expire_time),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned define_rule__field_indices_by_name[] = {
  3,   /* field[3] = enable */
  8,   /* field[8] = expire_time */
  0,   /* field[0] = id */
  4,   /* field[4] = level */
  5,   /* field[5] = log_type */
  7,   /* field[7] = match_option_list */
  2,   /* field[2] = mode */
  6,   /* field[6] = name */
  1,   /* field[1] = seq */
};
static const ProtobufCIntRange define_rule__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor define_rule__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DefineRule",
  "DefineRule",
  "DefineRule",
  "",
  sizeof(DefineRule),
  9,
  define_rule__field_descriptors,
  define_rule__field_indices_by_name,
  1,  define_rule__number_ranges,
  (ProtobufCMessageInit) define_rule__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl_certificate__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SslCertificate, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SslCertificate, cert_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SslCertificate, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_path",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SslCertificate, cert_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_path",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SslCertificate, key_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_password",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SslCertificate, cert_password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl_certificate__field_indices_by_name[] = {
  1,   /* field[1] = cert_name */
  5,   /* field[5] = cert_password */
  3,   /* field[3] = cert_path */
  2,   /* field[2] = enable */
  0,   /* field[0] = id */
  4,   /* field[4] = key_path */
};
static const ProtobufCIntRange ssl_certificate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ssl_certificate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SslCertificate",
  "SslCertificate",
  "SslCertificate",
  "",
  sizeof(SslCertificate),
  6,
  ssl_certificate__field_descriptors,
  ssl_certificate__field_indices_by_name,
  1,  ssl_certificate__number_ranges,
  (ProtobufCMessageInit) ssl_certificate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bizserver__field_descriptors[3] =
{
  {
    "protocol",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Bizserver, protocol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Bizserver, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Bizserver, port),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bizserver__field_indices_by_name[] = {
  1,   /* field[1] = address */
  2,   /* field[2] = port */
  0,   /* field[0] = protocol */
};
static const ProtobufCIntRange bizserver__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bizserver__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bizserver",
  "Bizserver",
  "Bizserver",
  "",
  sizeof(Bizserver),
  3,
  bizserver__field_descriptors,
  bizserver__field_indices_by_name,
  1,  bizserver__number_ranges,
  (ProtobufCMessageInit) bizserver__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor attack_detect__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AttackDetect, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AttackDetect, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AttackDetect, block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AttackDetect, log),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned attack_detect__field_indices_by_name[] = {
  2,   /* field[2] = block */
  1,   /* field[1] = enable */
  3,   /* field[3] = log */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange attack_detect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor attack_detect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AttackDetect",
  "AttackDetect",
  "AttackDetect",
  "",
  sizeof(AttackDetect),
  4,
  attack_detect__field_descriptors,
  attack_detect__field_indices_by_name,
  1,  attack_detect__number_ranges,
  (ProtobufCMessageInit) attack_detect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor site_security__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SiteSecurity, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SiteSecurity, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decode_type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SiteSecurity, decode_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SiteSecurity, block_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attack_detect_list",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SiteSecurity, n_attack_detect_list),
    offsetof(SiteSecurity, attack_detect_list),
    &attack_detect__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "http_req_body_detect",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SiteSecurity, http_req_body_detect),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned site_security__field_indices_by_name[] = {
  4,   /* field[4] = attack_detect_list */
  3,   /* field[3] = block_type */
  2,   /* field[2] = decode_type */
  5,   /* field[5] = http_req_body_detect */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange site_security__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor site_security__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SiteSecurity",
  "SiteSecurity",
  "SiteSecurity",
  "",
  sizeof(SiteSecurity),
  6,
  site_security__field_descriptors,
  site_security__field_indices_by_name,
  1,  site_security__number_ranges,
  (ProtobufCMessageInit) site_security__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor predef_sign_rule__field_descriptors[2] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PredefSignRule, action),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "predef_sign_rule_path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PredefSignRule, predef_sign_rule_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned predef_sign_rule__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = predef_sign_rule_path */
};
static const ProtobufCIntRange predef_sign_rule__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor predef_sign_rule__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PredefSignRule",
  "PredefSignRule",
  "PredefSignRule",
  "",
  sizeof(PredefSignRule),
  2,
  predef_sign_rule__field_descriptors,
  predef_sign_rule__field_indices_by_name,
  1,  predef_sign_rule__number_ranges,
  (ProtobufCMessageInit) predef_sign_rule__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor virtual_service__field_descriptors[12] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VirtualService, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VirtualService, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bind_domain",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VirtualService, bind_domain),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VirtualService, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssl_enable",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VirtualService, ssl_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ports",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VirtualService, ports),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cw_ssl_certificate",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VirtualService, n_cw_ssl_certificate),
    offsetof(VirtualService, cw_ssl_certificate),
    &ssl_certificate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssl_version",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VirtualService, ssl_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssl_cipher",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VirtualService, ssl_cipher),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response_type",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VirtualService, response_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bizserver_list",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VirtualService, n_bizserver_list),
    offsetof(VirtualService, bizserver_list),
    &bizserver__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cw_site_security",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VirtualService, n_cw_site_security),
    offsetof(VirtualService, cw_site_security),
    &site_security__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned virtual_service__field_indices_by_name[] = {
  2,   /* field[2] = bind_domain */
  10,   /* field[10] = bizserver_list */
  11,   /* field[11] = cw_site_security */
  6,   /* field[6] = cw_ssl_certificate */
  3,   /* field[3] = enable */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  5,   /* field[5] = ports */
  9,   /* field[9] = response_type */
  8,   /* field[8] = ssl_cipher */
  4,   /* field[4] = ssl_enable */
  7,   /* field[7] = ssl_version */
};
static const ProtobufCIntRange virtual_service__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor virtual_service__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VirtualService",
  "VirtualService",
  "VirtualService",
  "",
  sizeof(VirtualService),
  12,
  virtual_service__field_descriptors,
  virtual_service__field_indices_by_name,
  1,  virtual_service__number_ranges,
  (ProtobufCMessageInit) virtual_service__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor virtual_service_res__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VirtualServiceRes, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned virtual_service_res__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange virtual_service_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor virtual_service_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VirtualServiceRes",
  "VirtualServiceRes",
  "VirtualServiceRes",
  "",
  sizeof(VirtualServiceRes),
  1,
  virtual_service_res__field_descriptors,
  virtual_service_res__field_indices_by_name,
  1,  virtual_service_res__number_ranges,
  (ProtobufCMessageInit) virtual_service_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cw_config__field_descriptors[11] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CwConfig, action),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dnsConfig",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, dnsconfig),
    &dns_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "manageService",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, manageservice),
    &manage_service__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "defaultGateway",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, defaultgateway),
    &default_gateway__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "staticRoute",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, staticroute),
    &static_route__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interface",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, interface),
    &interface__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "defineRule",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, definerule),
    &define_rule__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sslCertificate",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, sslcertificate),
    &ssl_certificate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "siteSecurity",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, sitesecurity),
    &site_security__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "predefSignRule",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, predefsignrule),
    &predef_sign_rule__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "virtualService",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CwConfig, virtualservice),
    &virtual_service__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cw_config__field_indices_by_name[] = {
  0,   /* field[0] = action */
  3,   /* field[3] = defaultGateway */
  6,   /* field[6] = defineRule */
  1,   /* field[1] = dnsConfig */
  5,   /* field[5] = interface */
  2,   /* field[2] = manageService */
  9,   /* field[9] = predefSignRule */
  8,   /* field[8] = siteSecurity */
  7,   /* field[7] = sslCertificate */
  4,   /* field[4] = staticRoute */
  10,   /* field[10] = virtualService */
};
static const ProtobufCIntRange cw_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor cw_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CwConfig",
  "CwConfig",
  "CwConfig",
  "",
  sizeof(CwConfig),
  11,
  cw_config__field_descriptors,
  cw_config__field_indices_by_name,
  1,  cw_config__number_ranges,
  (ProtobufCMessageInit) cw_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
