/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

#ifndef PROTOBUF_C_test_2eproto__INCLUDED
#define PROTOBUF_C_test_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Name Name;
typedef struct _Person Person;


/* --- enums --- */


/* --- messages --- */

struct  _Name
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  int32_t age;
};
#define NAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&name__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0 }


struct  _Person
{
  ProtobufCMessage base;
  int32_t id;
  size_t n_name;
  Name **name;
};
#define PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&person__descriptor) \
    , 0, 0,NULL }


/* Name methods */
void   name__init
                     (Name         *message);
size_t name__get_packed_size
                     (const Name   *message);
size_t name__pack
                     (const Name   *message,
                      uint8_t             *out);
size_t name__pack_to_buffer
                     (const Name   *message,
                      ProtobufCBuffer     *buffer);
Name *
       name__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   name__free_unpacked
                     (Name *message,
                      ProtobufCAllocator *allocator);
/* Person methods */
void   person__init
                     (Person         *message);
size_t person__get_packed_size
                     (const Person   *message);
size_t person__pack
                     (const Person   *message,
                      uint8_t             *out);
size_t person__pack_to_buffer
                     (const Person   *message,
                      ProtobufCBuffer     *buffer);
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Name_Closure)
                 (const Name *message,
                  void *closure_data);
typedef void (*Person_Closure)
                 (const Person *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor name__descriptor;
extern const ProtobufCMessageDescriptor person__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test_2eproto__INCLUDED */
